export enum END_POINTS {
    BLANK = '/',
    AWS = '/aws',
    ENC_DEC = '/api/v1/enc-dec',
    MAIN = '/api/v1',
    AUTH = '/auth',
    ALL = '*',
    USER = '/user',
    ADMIN = '/admin',
    GET_USERS = '/get-users',
    DELETE_USER = '/delete-user/:id',
    EDIT_USER = '/edit-user/:id',
    CRAETE_USER = '/create-user',
    LOGIN = '/login',
    ENCRIPTIONS = '/encryption',
    DECRPTIONS = '/decryption',
    COUNTRY = '/country',
    CITY = '/city',
}
